package emissary.test.core.junit5;

import emissary.core.IBaseDataObject;
import emissary.core.IBaseDataObjectXmlCodecs;
import emissary.core.IBaseDataObjectXmlHelper;
import emissary.place.IServiceProviderPlace;
import emissary.util.DisposeHelper;
import emissary.util.io.ResourceReader;

import jakarta.annotation.Nullable;
import org.apache.commons.compress.utils.SeekableInMemoryByteChannel;
import org.jdom2.Document;
import org.jdom2.Element;
import org.jdom2.JDOMException;
import org.jdom2.input.SAXBuilder;
import org.jdom2.input.sax.XMLReaders;
import org.jdom2.output.Format;
import org.jdom2.output.LineSeparator;
import org.jdom2.output.XMLOutputter;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.nio.channels.FileChannel;
import java.nio.file.Path;
import java.nio.file.StandardOpenOption;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.concurrent.atomic.AtomicReference;

import static emissary.core.constants.IbdoXmlElementNames.ANSWERS;
import static emissary.core.constants.IbdoXmlElementNames.DATA_FILE;
import static emissary.core.constants.IbdoXmlElementNames.NOMETA;
import static emissary.core.constants.IbdoXmlElementNames.NOVIEW;
import static emissary.core.constants.IbdoXmlElementNames.SETUP;
import static org.junit.jupiter.api.Assertions.fail;

public abstract class AnswerGenerator {

    protected static final Logger logger = LoggerFactory.getLogger(AnswerGenerator.class);

    /** Open options for (over-)writing answers XML */
    private static final Set<StandardOpenOption> CREATE_WRITE_TRUNCATE = new HashSet<>(Arrays.asList(StandardOpenOption.CREATE,
            StandardOpenOption.WRITE, StandardOpenOption.TRUNCATE_EXISTING));

    /** test/resources folder */
    private static final Path TEST_RESX = getTestResx();

    /**
     * Actually generate the answer file for a given resource
     * <p>
     * Takes initial form and final forms from the filename
     *
     * @param resource to generate against
     * @param place the place under test
     * @param initialIbdo for 'setup' section
     * @param encoders for encoding ibdo into XML
     * @param answerFileClassRef answer file class (if different from data class)
     * @param logbackLoggerName name of logger to use
     */
    public abstract void generateAnswerFiles(String resource, IServiceProviderPlace place, IBaseDataObject initialIbdo,
            IBaseDataObjectXmlCodecs.ElementEncoders encoders, AtomicReference<Class<?>> answerFileClassRef, String logbackLoggerName);

    public void generateAnswerFiles(String datResource, String answerResource, IServiceProviderPlace place, IBaseDataObject initialIbdo,
            IBaseDataObjectXmlCodecs.ElementEncoders encoders, AtomicReference<Class<?>> answerFileClassRef, String logbackLoggerName) {
        generateAnswerFiles(datResource, place, initialIbdo, encoders, answerFileClassRef, logbackLoggerName);
    }

    @Nullable
    public Document getAnswerDocumentFor(final String resource, final AtomicReference<Class<?>> answerFileClassRef) {
        try {
            /* XML builder to read XML answer file in */
            final Path path = getXmlPath(resource, answerFileClassRef);
            return path == null ? null : new SAXBuilder(XMLReaders.NONVALIDATING).build(path.toFile());
        } catch (final JDOMException | IOException e) {
            // Fail if invalid XML document
            fail(String.format("No valid answer document provided for %s", resource), e);
            return null;
        }
    }

    /**
     * Allow the initial IBDO to be overridden before serializing to XML.
     * <p>
     * In the default case, we null out the data in the BDO which will force the data to be loaded from the .dat file
     * instead.
     *
     * @param resource path to the dat file
     * @param initialIbdo to tweak
     */
    protected void tweakInitialIbdoBeforeSerialization(final String resource, final IBaseDataObject initialIbdo) {
        initialIbdo.clearData();
    }


    /**
     * Allow the generated IBDO to be overridden - for example, adding certain field values. Will modify the provided IBDO.
     * <p>
     * This is used in the simple case to set the current form for the final object to be taken from the file name. If the
     * test worked correctly no change will be made, but if there is a discrepancy this will be highlighted afterwards when
     * the diff takes place.
     *
     * @param resource path to the dat file
     * @param finalIbdo the existing final BDO after it's been processed by a place
     */
    protected abstract void tweakFinalIbdoBeforeSerialization(String resource, IBaseDataObject finalIbdo);

    /**
     * Allow the children generated by the place to be overridden before serializing to XML.
     * <p>
     * In the default case, do nothing.
     *
     * @param resource path to the dat file
     * @param children to tweak
     */
    protected void tweakFinalResultsBeforeSerialization(final String resource, final List<IBaseDataObject> children) {
        // No-op unless overridden
    }

    /**
     * Allows the log events generated by the place to be modified before serializing to XML.
     * <p>
     * In the default case, do nothing.
     *
     * @param resource path to the dat file
     * @param simplifiedLogEvents to tweak
     */
    protected void tweakFinalLogEventsBeforeSerialization(final String resource, final List<LogbackTester.SimplifiedLogEvent> simplifiedLogEvents) {
        // No-op unless overridden
    }

    /**
     * Dynamically finds the src/test/resources directory to write the XML to.
     * <p>
     * Running locally in an IDE, PROJECT_BASE will likely point to {@code src/main/}
     *
     * Running in Maven/Docker it will most likely point to {@code target/}
     *
     * @return a path to write XML output to
     */
    public static Path getTestResx() {
        // Gets us the parent folder to PROJECT_BASE
        Path pathBuilder = Path.of(System.getenv("PROJECT_BASE"));
        // If in Docker, we need to go into src - we're probably already in it otherwise
        if (pathBuilder.endsWith("main")) { // Docker
            pathBuilder = pathBuilder.getParent();
        } else if (pathBuilder.getFileName().toString().contains("target")) {
            pathBuilder = pathBuilder.getParent().resolve("src");
        }
        // Append test/resources to finish the path off
        return pathBuilder.resolve("test/resources");
    }

    /**
     * Generate the relevant XML and write to disk.
     *
     * @param resource referencing the DAT file
     * @param initialIbdo for 'setup' section
     * @param finalIbdo for 'answers' section
     * @param results for 'answers' section
     * @param logEvents events to send to the LogbackTester
     * @param encoders for encoding ibdo into XML
     * @param answerFileClassRef answer file class (if different from data class)
     */
    public static void writeAnswerXml(String resource, IBaseDataObject initialIbdo, IBaseDataObject finalIbdo,
            List<IBaseDataObject> results, List<LogbackTester.SimplifiedLogEvent> logEvents, IBaseDataObjectXmlCodecs.ElementEncoders encoders,
            @Nullable AtomicReference<Class<?>> answerFileClassRef) {
        final Element rootElement = IBaseDataObjectXmlHelper.xmlElementFromIbdo(finalIbdo, results, initialIbdo, encoders);
        final Element answerElement = rootElement.getChild(ANSWERS);

        LogbackTester.SimplifiedLogEvent.toXml(logEvents).forEach(answerElement::addContent);

        // Generate the full XML (setup & answers from before & after)
        final byte[] xmlContent = bytesFromDocument(new Document(rootElement));
        // Write out the XML to disk
        writeXml(resource, xmlContent, answerFileClassRef);
    }

    /**
     * Generate the relevant XML and write to disk.
     *
     * @param datResource referencing the DAT file
     * @param answerResource referencing the answer file
     * @param existingDoc referencing the existing xml file
     * @param initialIbdo for 'setup' section
     * @param finalIbdo for 'answers' section
     * @param finalResults for 'answers' section
     * @param finalLogEvents events to send to the LogbackTester
     * @param encoders for encoding ibdo into XML
     * @param answerFileClassRef answer file class (if different from data class)
     */
    public static void writeAnswerXml(String datResource, String answerResource, Document existingDoc, IBaseDataObject initialIbdo,
            IBaseDataObject finalIbdo, List<IBaseDataObject> finalResults, List<LogbackTester.SimplifiedLogEvent> finalLogEvents,
            IBaseDataObjectXmlCodecs.ElementEncoders encoders, @Nullable AtomicReference<Class<?>> answerFileClassRef) {

        final Element existingRoot = existingDoc.getRootElement();
        final Element dataFileElement = existingRoot.getChild(DATA_FILE);
        final Element setupElement = existingRoot.getChild(SETUP);
        if (setupElement == null) {
            logger.trace("Existing XML for {} does not contain a <setup> element.", datResource);
        }

        // Generate a fresh root using the helper (we pass null for initialIbdo to keep the answer section clean)
        final Element newFullRoot = IBaseDataObjectXmlHelper.xmlElementFromIbdo(finalIbdo, finalResults, initialIbdo, encoders);
        final Element newAnswerElement = newFullRoot.getChild(ANSWERS);

        final Element answerElement = existingRoot.getChild(ANSWERS);
        if (answerElement != null && newAnswerElement != null) {
            List<Element> originalChildren = new ArrayList<>(answerElement.getChildren());

            for (Element oldChild : originalChildren) {
                // Fail-fast safety check for OS-specific markers anywhere in the subtree
                if (hasOsReleaseAttribute(oldChild)) {
                    throw new UnsupportedOperationException("Cannot generate answers for OS specific output");
                }

                // Recursively find and copy nometa/noview tags
                copyTargetedElementsIfPathExists(oldChild, newAnswerElement);
            }
        }

        // Add log events to the new answer section
        LogbackTester.SimplifiedLogEvent.toXml(finalLogEvents).forEach(newAnswerElement::addContent);

        // Construct the merged Document
        final Element mergedRoot = new Element(existingRoot.getName(), existingRoot.getNamespace());
        if (dataFileElement != null) {
            mergedRoot.addContent(dataFileElement.detach());
        }
        if (setupElement != null) {
            mergedRoot.addContent(setupElement.detach());
        }
        mergedRoot.addContent(newAnswerElement.detach());

        // Write back to answer file
        final byte[] xmlContent = bytesFromDocument(new Document(mergedRoot));
        writeXml(answerResource == null ? datResource : answerResource, xmlContent, answerFileClassRef);
    }

    /**
     * Recursively traverses the old XML tree and copies nometa/noview elements into the new tree ONLY if the matching
     * parent path already exists.
     */
    private static void copyTargetedElementsIfPathExists(Element oldElement, Element newParent) {
        String name = oldElement.getName();

        if (NOMETA.equals(name) || NOVIEW.equals(name)) {
            newParent.addContent(oldElement.detach());
            return;
        }

        // Is there a nested nometa/noview further down this branch?
        if (containsNometaOrNoview(oldElement)) {
            // Look for the matching container in the new tree
            Element existingNewContainer = newParent.getChild(name);

            // If the path does not exist in the new tree, abandon this branch
            if (existingNewContainer == null) {
                return;
            }

            // find the leaf nodes
            List<Element> oldChildren = new ArrayList<>(oldElement.getChildren());
            for (Element oldChild : oldChildren) {
                copyTargetedElementsIfPathExists(oldChild, existingNewContainer);
            }
        }
    }

    private static boolean hasOsReleaseAttribute(Element element) {
        if (element.getAttribute("os-release") != null) {
            return true;
        }
        for (Element child : element.getChildren()) {
            if (hasOsReleaseAttribute(child)) {
                return true;
            }
        }
        return false;
    }

    private static boolean containsNometaOrNoview(Element element) {
        String name = element.getName();
        if (NOMETA.equals(name) || NOVIEW.equals(name)) {
            return true;
        }
        for (Element child : element.getChildren()) {
            if (containsNometaOrNoview(child)) {
                return true;
            }
        }
        return false;
    }

    @Nullable
    public static byte[] bytesFromDocument(Document jdom) {
        final Format format = Format.getPrettyFormat().setLineSeparator(LineSeparator.UNIX);
        final XMLOutputter outputter = new XMLOutputter(format);

        try (ByteArrayOutputStream os = new ByteArrayOutputStream()) {
            outputter.output(jdom, os);
            return os.toByteArray();
        } catch (IOException iox) {
            return null;
        }
    }

    /**
     * Helper method to write XML for a given DAT file.
     *
     * @param resource referencing the DAT file
     * @param xmlContent to write to the XML answer file
     * @param answerFileClassRef answer file class (if different from data class)
     */
    public static void writeXml(String resource, byte[] xmlContent, @Nullable AtomicReference<Class<?>> answerFileClassRef) {
        final Path path = getXmlPath(resource, answerFileClassRef);
        if (path == null) {
            fail(String.format("Could not get path for resource = %s", resource));
        }
        logger.info("Writing answers file to path: {}", path);
        try (FileChannel fc = FileChannel.open(path, CREATE_WRITE_TRUNCATE);
                SeekableInMemoryByteChannel simbc = new SeekableInMemoryByteChannel(xmlContent)) {
            fc.transferFrom(simbc, 0, simbc.size());
        } catch (final IOException ioe) {
            fail(String.format("Couldn't write XML answer file for resource: %s", resource), ioe);
        }
    }

    /**
     * Gets the XML filename/path for the given resource (a .dat file)
     *
     * @param resource path to the .dat file
     * @param answerFileClassRef answer file class (if different from data class)
     * @return path to the corresponding .xml file
     */
    @Nullable
    public static Path getXmlPath(String resource, @Nullable AtomicReference<Class<?>> answerFileClassRef) {

        if (resource.endsWith(ResourceReader.XML_SUFFIX)) {
            logger.debug("Resource is the answer file {}", resource);
            return TEST_RESX.resolve(resource);
        }

        final int datPos = resource.lastIndexOf(ResourceReader.DATA_SUFFIX);
        if (datPos == -1) {
            logger.debug("Resource is not a DATA file {}", resource);
            return null;
        }

        String xmlPath;
        if (answerFileClassRef == null) {
            xmlPath = resource.substring(0, datPos) + ResourceReader.XML_SUFFIX;
        } else {
            String ansPath = answerFileClassRef.get().getName().replace(".", "/");
            int testNamePos = resource.lastIndexOf("/");
            xmlPath = ansPath + resource.substring(testNamePos, datPos) + ResourceReader.XML_SUFFIX;
        }
        return TEST_RESX.resolve(xmlPath);
    }

    /**
     * Default behavior to fix dispose runnables to change "variant" to "invariant"
     *
     * @param ibdo the base data object containing dispose runnables
     */
    public static void fixDisposeRunnables(IBaseDataObject ibdo) {
        if (ibdo.hasParameter(DisposeHelper.KEY)) {
            final List<Object> values = ibdo.getParameter(DisposeHelper.KEY);
            final List<String> newValues = new ArrayList<>();

            for (Object o : values) {
                if (null != o) {
                    newValues.add(o.getClass().getName());
                }
            }

            ibdo.putParameter(DisposeHelper.KEY, newValues);
        }
    }
}
