package emissary.test.core.junit5;

import emissary.core.DataObjectFactory;
import emissary.core.DiffCheckConfiguration;
import emissary.core.IBaseDataObject;
import emissary.core.IBaseDataObjectDiffHelper;
import emissary.core.IBaseDataObjectXmlCodecs;
import emissary.core.IBaseDataObjectXmlHelper;
import emissary.core.channels.FileChannelFactory;
import emissary.core.channels.SeekableByteChannelFactory;
import emissary.kff.KffDataObjectHandler;
import emissary.place.IServiceProviderPlace;
import emissary.test.core.junit5.LogbackTester.SimplifiedLogEvent;
import emissary.util.ByteUtil;
import emissary.util.PlaceComparisonHelper;
import emissary.util.io.ResourceReader;
import emissary.util.os.OSReleaseUtil;

import com.google.errorprone.annotations.ForOverride;
import jakarta.annotation.Nullable;
import org.apache.commons.io.FilenameUtils;
import org.apache.commons.io.IOUtils;
import org.apache.commons.lang3.ArrayUtils;
import org.apache.commons.lang3.StringUtils;
import org.jdom2.DataConversionException;
import org.jdom2.Document;
import org.jdom2.Element;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.net.URISyntaxException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.Optional;
import java.util.stream.Stream;

import static emissary.core.IBaseDataObjectXmlCodecs.ALT_DEFAULT_ELEMENT_ENCODERS;
import static emissary.core.IBaseDataObjectXmlCodecs.ALWAYS_SHA256_ELEMENT_ENCODERS;
import static emissary.core.IBaseDataObjectXmlCodecs.DEFAULT_ELEMENT_DECODERS;
import static emissary.core.IBaseDataObjectXmlCodecs.SHA256_ELEMENT_ENCODERS;
import static emissary.core.constants.IbdoXmlElementNames.ANSWERS;
import static emissary.core.constants.IbdoXmlElementNames.BAD_ALT_VIEW;
import static emissary.core.constants.IbdoXmlElementNames.DATA_FILE;
import static emissary.core.constants.IbdoXmlElementNames.FILE_TYPE;
import static emissary.core.constants.IbdoXmlElementNames.INITIAL_FORM;
import static emissary.core.constants.IbdoXmlElementNames.INPUT_ALT_VIEW;
import static emissary.core.constants.IbdoXmlElementNames.SETUP;
import static emissary.test.core.junit5.AnswerGenerator.fixDisposeRunnables;
import static org.junit.jupiter.api.Assertions.assertIterableEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.fail;

public abstract class ExtractionTest extends UnitTest {

    protected static final Logger logger = LoggerFactory.getLogger(ExtractionTest.class);

    private static final byte[] INCORRECT_VIEW_MESSAGE = "This is the incorrect view, the place should not have processed this view".getBytes();

    private volatile AnswerGenerator answerGenerator;

    protected boolean strict = false;
    @Nullable
    protected String generateAnswerFiles = null;
    @Nullable
    protected String loggerToCapture = null;

    /**
     * The list of actual logEvents generated by executing the place.
     */
    protected List<SimplifiedLogEvent> actualSimplifiedLogEvents;

    protected final KffDataObjectHandler kff = new KffDataObjectHandler(
            KffDataObjectHandler.TRUNCATE_KNOWN_DATA,
            KffDataObjectHandler.SET_FORM_WHEN_KNOWN,
            KffDataObjectHandler.SET_FILE_TYPE);

    @Nullable
    protected IServiceProviderPlace place = null;
    @Nullable
    public static final String SYSTEM_OS_RELEASE;
    @Nullable
    public static final String MAJOR_OS_VERSION;

    static {
        if (OSReleaseUtil.isUbuntu()) {
            SYSTEM_OS_RELEASE = "ubuntu";
            MAJOR_OS_VERSION = OSReleaseUtil.getMajorReleaseVersion();
        } else if (OSReleaseUtil.isCentOs()) {
            SYSTEM_OS_RELEASE = "centos";
            MAJOR_OS_VERSION = OSReleaseUtil.getMajorReleaseVersion();
        } else if (OSReleaseUtil.isRhel()) {
            SYSTEM_OS_RELEASE = "rhel";
            MAJOR_OS_VERSION = OSReleaseUtil.getMajorReleaseVersion();
        } else if (OSReleaseUtil.isMac()) {
            SYSTEM_OS_RELEASE = "mac";
            MAJOR_OS_VERSION = OSReleaseUtil.getMajorReleaseVersion();
        } else {
            SYSTEM_OS_RELEASE = null;
            MAJOR_OS_VERSION = null;
        }
    }

    /**
     * Indicates whether the test is executing in strict (regression) or lenient (extraction) mode.
     * <p>
     * <strong>Strict (Regression) Mode:</strong> Compares the entire {@code IBaseDataObject} snapshot against the XML. The
     * XML must define the exact output of the processing place — no more and no less. Any unexpected metadata fields or
     * data variants will trigger a test failure.
     * <p>
     * <strong>Lenient (Extraction) Mode:</strong> Evaluates specific field presence, values, or absence without enforcing
     * complete snapshot compliance.
     *
     * @return {@code true} for regression mode, {@code false} otherwise
     */
    public boolean isStrict() {
        return this.strict;
    }

    /**
     * Sets the processing verification strategy for this test instance.
     * <p>
     * This method allows downstream test configurations to choose between full-object tracking or localized extraction
     * validation.
     *
     * @param strict {@code true} to enforce strict/regression mode (exact-match validation); {@code false} to enforce
     *        lenient/extraction mode (subset validation).
     * @see #isStrict() for a detailed breakdown of the behavioral differences between modes.
     */
    public void setStrict(boolean strict) {
        this.strict = strict;
    }

    /**
     * Gets the current answer file generation execution mode.
     * <p>
     * The value is resolved in the following priority order:
     * <ol>
     * <li>Directly assigned value via {@link #setGenerateAnswerFiles(String)}</li>
     * <li>The system property value assigned via {@code -DgenerateAnswers=...}</li>
     * <li>The default value of {@code "false"} (bypassing answer generation)</li>
     * </ol>
     * <p>
     * Supported modes include:
     * <ul>
     * <li>{@code "all"} or {@code "true"}: Generates both strict and lenient answer files.</li>
     * <li>{@code "strict"} or {@code "regression"}: Generates answer files only if the test is running in strict mode.</li>
     * <li>{@code "lenient"} or {@code "extraction"}: Generates answer files only if the test is running in lenient
     * mode.</li>
     * <li>{@code "false"}: Skips all answer file generation routines (default).</li>
     * </ul>
     * * @return a lowercase string representing the answer file generation mode.
     */
    public String getGenerateAnswerFiles() {
        if (generateAnswerFiles == null) {
            generateAnswerFiles = System.getProperty("generateAnswers", "false").toLowerCase(Locale.getDefault());
        }
        return generateAnswerFiles;
    }

    /**
     * Overrides the answer file generation execution mode for this test instance.
     *
     * @param generateAnswerFiles the target generation mode; accepted values are {@code "all"}, {@code "true"},
     *        {@code "strict"}, {@code "regression"}, {@code "lenient"}, {@code "extraction"}, or {@code "false"}.
     * @see #getGenerateAnswerFiles() for detailed descriptions of each mode's behavioral impact.
     */
    public void setGenerateAnswerFiles(String generateAnswerFiles) {
        this.generateAnswerFiles = (generateAnswerFiles != null) ? generateAnswerFiles.toLowerCase(Locale.getDefault()) : "false";
    }

    /**
     * Configuration of {@link IBaseDataObjectDiffHelper} needed in strict mode
     *
     * @return diff helper configuration
     */
    public DiffCheckConfiguration getDiffCheck() {
        return DiffCheckConfiguration.configure().enableData().enableKeyValueParameterDiff().setStrict(isStrict()).build();
    }

    @Override
    public String getAnswerXsd() {
        return isStrict() ? "emissary/test/core/schemas/regression.xsd" : super.getAnswerXsd();
    }

    /**
     * Override this or set the generateAnswers system property to true to generate XML for data files.
     * <p>
     * Optionally, to generate answers file without changing code run {@code mvn clean test -DgenerateAnswers=true}
     *
     * @return defaults to false if no XML should be generated (i.e. normal case of executing tests) or true to generate
     *         automatically
     */
    protected boolean generateAnswers() {
        String generateAnswerFiles = getGenerateAnswerFiles();

        if ("false".equals(generateAnswerFiles) || createAnswerGenerator() == null) {
            return false;
        }

        switch (generateAnswerFiles) {
            case "all":
            case "true":
                return true;
            case "strict":
            case "regression":
                return isStrict();
            case "lenient":
            case "extraction":
                return !isStrict();
            default:
                logger.warn("Unknown generateAnswers mode: '{}'. Defaulting to false.", generateAnswerFiles);
                return false;
        }
    }

    @Nullable
    protected AnswerGenerator createAnswerGenerator() {
        return isStrict() ? new RegressionTestAnswerGenerator() : new ExtractionTestAnswerGenerator();
    }

    protected AnswerGenerator getAnswerGenerator() {
        if (answerGenerator == null) {
            answerGenerator = createAnswerGenerator();
        }
        return answerGenerator;
    }

    /**
     * This method returns the XML element decoders.
     *
     * @return the XML element decoders.
     */
    @Deprecated
    protected IBaseDataObjectXmlCodecs.ElementDecoders getDecoders() {
        return DEFAULT_ELEMENT_DECODERS;
    }

    /**
     * This method returns the XML element decoders.
     *
     * @param resource the "resource" currently be tested.
     * @return the XML element decoders.
     */
    protected IBaseDataObjectXmlCodecs.ElementDecoders getDecoders(final String resource) {
        return getDecoders();
    }

    /**
     * This method returns the XML element encoders.
     *
     * @return the XML element encoders.
     */
    @Deprecated
    protected IBaseDataObjectXmlCodecs.ElementEncoders getEncoders() {
        return isStrict() ? SHA256_ELEMENT_ENCODERS : ALT_DEFAULT_ELEMENT_ENCODERS;
    }

    /**
     * This method returns the XML element encoders.
     *
     * @param resource the "resource" currently be tested.
     * @return the XML element encoders.
     */
    protected IBaseDataObjectXmlCodecs.ElementEncoders getEncoders(final String resource) {
        return getEncoders();
    }

    @BeforeEach
    public void setUpPlace() throws Exception {
        place = createPlace();
    }

    @AfterEach
    public void tearDownPlace() {
        if (place != null) {
            place.shutDown();
            place = null;
        }
    }

    public abstract IServiceProviderPlace createPlace() throws IOException;

    public static Stream<? extends Arguments> data() {
        return getMyXmlTestParameterFiles(ExtractionTest.class);
    }

    /**
     * Allow overriding the initial form in extensions to this test.
     *
     * By default, get the initial form from the filename in the form {@code INITIAL_FORM@2.dat} where {@code INITIAL_FORM}
     * will be the initial form.
     *
     * @param resource to get the form from
     * @return the initial form
     */
    @ForOverride
    @Nullable
    protected String getInitialForm(final String resource) {
        if (!isStrict()) {
            return resource.replaceAll("^.*/([^/@]+)(@\\d+)?\\.dat$", "$1");
        }

        InitialFinalFormFormat datFile = new InitialFinalFormFormat(getResourcePath(resource));
        return datFile.getInitialForm();
    }

    /**
     * Allow the initial IBDO to be overridden - for example, adding additional previous forms
     * <p>
     * This is used in the simple case to generate an IBDO from the file on disk and override the filename
     *
     * @param resource path to the dat file
     * @return the initial IBDO
     */
    @Nullable
    protected IBaseDataObject getInitialIbdo(final String resource) {
        Path path = getResourcePath(resource);
        SeekableByteChannelFactory sbcf = FileChannelFactory.create(path);
        String initialForm = getInitialForm(resource);

        IBaseDataObject ibdo = IBaseDataObjectXmlHelper.createStandardInitialIbdo(sbcf, isStrict() ? "Classification" : null, initialForm, kff);
        ibdo.setChannelFactory(sbcf);

        if (isStrict()) {
            InitialFinalFormFormat datFile = new InitialFinalFormFormat(path);
            ibdo.setFilename(datFile.getOriginalFileName());
        } else {
            Document controlDoc = getRequiredAnswerDocument(resource);
            ibdo.setFilename(Path.of(resource).toString());
            setupPayload(ibdo, controlDoc);
        }

        return ibdo;
    }

    /**
     * This method returns the logger name to capture log events from or null if log events are not to be checked.
     *
     * @return the logger name to capture log events from or null (the default) if log events are not to be checked.
     */
    protected String getLogbackLoggerName() {
        return loggerToCapture;
    }

    /**
     * Set the logger name to capture log events from or null if log events are not to be checked.
     *
     * @param loggerToCapture the name of the logger to capture
     */
    protected void setLogbackLoggerName(String loggerToCapture) {
        this.loggerToCapture = loggerToCapture;
    }

    @ParameterizedTest(name = "{arguments}")
    @MethodSource("data")
    public void testExtractionPlace(String resource) {
        logger.debug("Running {} test on resource {}", place.getClass().getName(), resource);

        // Need a pair consisting of a .dat file and a .xml file (answers)
        Document controlDoc = getRequiredAnswerDocument(resource);

        // In XML-driven mode, resolve which .dat to use (via <dataFile> or same-name fallback).
        // In legacy DAT-driven mode the resource is already the .dat path.
        String datResource = resource.endsWith(ResourceReader.XML_SUFFIX)
                ? getDatResourceFor(resource, controlDoc)
                : resource;

        if (generateAnswers()) {
            getAnswerGenerator().generateAnswerFiles(datResource, resource, place, getInitialIbdo(datResource),
                    getEncoders(datResource), super.answerFileClassRef, getLogbackLoggerName());
        }

        try (InputStream doc = new ResourceReader().getResourceAsStream(datResource)) {
            byte[] data = IOUtils.toByteArray(doc);
            IBaseDataObject payload = DataObjectFactory.getInstance(data, datResource, getInitialForm(datResource));

            setupPayload(payload, controlDoc);
            processPreHook(payload, controlDoc);

            List<IBaseDataObject> attachments = processHeavyDutyHook(place, payload);

            processPostHook(payload, attachments);
            checkAnswersPreHook(controlDoc, payload, attachments, datResource);
            checkAnswers(controlDoc, payload, attachments, datResource);
            checkAnswersPostHook(controlDoc, payload, attachments, datResource);
        } catch (Exception ex) {
            logger.error("Error running test {}", datResource, ex);
            fail("Cannot run test " + datResource, ex);
        }
    }

    /**
     * Resolve the .dat resource path for an XML-driven test. Checks the {@code <dataFile>} element in the XML root; if
     * present, the value must be a bare filename (no path separators) and the file is resolved relative to the XML's
     * directory. If absent, falls back to the same-named .dat file in the same directory.
     *
     * @param xmlResource classpath resource path to the answer XML
     * @param answerDoc the parsed answer document
     * @return classpath resource path to the .dat file to use
     */
    protected String getDatResourceFor(final String xmlResource, final Document answerDoc) {
        Element root = answerDoc.getRootElement();
        String dataFileName = root.getChildTextTrim(DATA_FILE);
        if (StringUtils.isNotBlank(dataFileName)) {
            if (dataFileName.contains("/") || dataFileName.contains(File.separator)) {
                fail("dataFile must be a directory-local filename (no path separators): " + dataFileName);
            }
            return FilenameUtils.getPath(xmlResource) + dataFileName;
        }
        return xmlResource.substring(0, xmlResource.length() - ResourceReader.XML_SUFFIX.length())
                + ResourceReader.DATA_SUFFIX;
    }

    @Nullable
    protected Path getResourcePath(String resource) {
        try {
            return Path.of(new ResourceReader().getResource(resource).toURI());
        } catch (URISyntaxException | NullPointerException e) {
            fail("Failed to resolve resource path: " + resource, e);
            return null;
        }
    }

    protected Document getRequiredAnswerDocument(String resource) {
        Document doc = getAnswerDocumentFor(resource);
        if (doc == null) {
            fail("No answers provided for test: " + resource);
        }
        return doc;
    }

    @Override
    protected Document getAnswerDocumentFor(final String resource) {
        if (generateAnswers()) {
            return getAnswerGenerator().getAnswerDocumentFor(resource, answerFileClassRef);
        }
        // XML-driven mode: resource IS the XML file
        if (resource.endsWith(ResourceReader.XML_SUFFIX)) {
            return getAnswerDocumentValidated(resource);
        }
        // Legacy DAT-driven mode: derive XML path from the .dat resource
        return super.getAnswerDocumentFor(resource);
    }

    protected void processPreHook(IBaseDataObject payload, Document controlDoc) {
        // Nothing to do here
    }

    protected void processPostHook(IBaseDataObject payload, List<IBaseDataObject> attachments) {
        // Nothing to do here
    }

    protected List<IBaseDataObject> processHeavyDutyHook(IServiceProviderPlace place, IBaseDataObject payload) throws Exception {
        if (getLogbackLoggerName() == null) {
            actualSimplifiedLogEvents = new ArrayList<>();
            return place.agentProcessHeavyDuty(payload);
        } else {
            try (LogbackTester logbackTester = new LogbackTester(getLogbackLoggerName())) {
                final List<IBaseDataObject> attachments = place.agentProcessHeavyDuty(payload);
                actualSimplifiedLogEvents = logbackTester.getSimplifiedLogEvents();
                return attachments;
            }
        }
    }

    /**
     * When the data is able to be retrieved from the XML (e.g. when getEncoders() returns the default encoders), then this
     * method should be empty. However, in this case getEncoders() is returning the sha256 encoders which means the original
     * data cannot be retrieved from the XML. Therefore, in order to test equivalence, all the non-printable data in the
     * IBaseDataObjects needs to be converted to a sha256 hash. The full encoders can be used by overriding the
     * checkAnswersPreHook(...) to be empty and overriding getEncoders() to return the DEFAULT_ELEMENT_ENCODERS.
     */
    protected void checkAnswersPreHook(Document answers, IBaseDataObject payload, List<IBaseDataObject> attachments, String tname) {

        if (getLogbackLoggerName() != null) {
            checkAnswersPreHookLogEvents(actualSimplifiedLogEvents);
        }

        IBaseDataObjectXmlCodecs.ElementEncoders encoders = getEncoders(tname);
        boolean alwaysHash = ALWAYS_SHA256_ELEMENT_ENCODERS.equals(encoders);

        // Only proceed if we are using a hashing encoder
        if (!alwaysHash && !SHA256_ELEMENT_ENCODERS.equals(encoders)) {
            return;
        }

        // Hash alternate views
        payload.getAlternateViews().forEach((viewName, bytes) -> hashIfNecessary(bytes, alwaysHash)
                .ifPresent(hash -> payload.addAlternateView(viewName, hash.getBytes(StandardCharsets.UTF_8))));

        // Hash primary data
        hashIfNecessary(payload.data(), alwaysHash).ifPresent(hash -> payload.setData(hash.getBytes(StandardCharsets.UTF_8)));

        // Hash extracted records
        Optional.ofNullable(payload.getExtractedRecords()).ifPresent(records -> records.forEach(rec -> hashIfNecessary(rec.data(), alwaysHash)
                .ifPresent(hash -> rec.setData(hash.getBytes(StandardCharsets.UTF_8)))));

        // Hash attachments
        Optional.ofNullable(attachments).ifPresent(atts -> atts.stream()
                .filter(att -> ByteUtil.hasNonPrintableValues(att.data()))
                .forEach(att -> hashIfNecessary(att.data(), alwaysHash)
                        .ifPresent(hash -> att.setData(hash.getBytes(StandardCharsets.UTF_8)))));

        fixDisposeRunnables(payload);
    }

    protected void checkAnswersPreHook(Element answers, IBaseDataObject payload, IBaseDataObject attachment, String tname) {
        // Nothing to do here
    }

    protected Optional<String> hashIfNecessary(byte[] data, boolean alwaysHash) {
        return hashBytesIfNonPrintable(data, alwaysHash);
    }

    /**
     * Generates a SHA 256 hash of the provided bytes if they contain any non-printable characters
     *
     * @param bytes the bytes to evaluate
     * @param alwaysHash overrides the non-printable check and always hashes the bytes.
     * @return a value optionally containing the generated hash
     */
    protected Optional<String> hashBytesIfNonPrintable(byte[] bytes, boolean alwaysHash) {
        if (ArrayUtils.isEmpty(bytes)) {
            return Optional.empty();
        }

        if (alwaysHash || ByteUtil.containsNonIndexableBytes(bytes)) {
            return Optional.ofNullable(ByteUtil.sha256Bytes(bytes));
        }

        return Optional.empty();
    }

    /**
     * This method allows log events to be modified prior to checkAnswers being called.
     *
     * In the default case, do nothing.
     *
     * @param simplifiedLogEvents the log events to be tweaked.
     */
    protected void checkAnswersPreHookLogEvents(List<SimplifiedLogEvent> simplifiedLogEvents) {
        // No-op unless overridden
    }

    protected void checkAnswersPostHook(Document answers, IBaseDataObject payload, List<IBaseDataObject> attachments, String tname) {
        // Nothing to do here
    }

    protected void checkAnswersPostHook(Element answers, IBaseDataObject payload, IBaseDataObject attachment, String tname) {
        // Nothing to do here
    }

    protected void checkAnswers(Document answers, IBaseDataObject payload, List<IBaseDataObject> attachments, String tname)
            throws DataConversionException {
        assertNotNull(place);
        Element root = answers.getRootElement();
        Element parent = root.getChild(ANSWERS);
        if (isStrict()) {
            assertNotNull(parent, "No 'answers' section found!");
            checkAnswersStrict(answers, payload, attachments, tname, parent);
        } else {
            checkAnswersLenient(Optional.ofNullable(parent).orElse(root), payload, attachments, tname);
        }
    }

    /**
     * LENIENT: Recursive element-based check for payload and attachments.
     *
     * @param parent XML element for the parent
     * @param payload The base data object
     * @param attachments The list of child base data objects
     * @param tname the path of the dat file
     * @throws DataConversionException data conversion from a string to value type fails
     */
    protected void checkAnswersLenient(Element parent, IBaseDataObject payload, List<IBaseDataObject> attachments, String tname)
            throws DataConversionException {

        DiffCheckConfiguration diffOptions = DiffCheckConfiguration.from(getDiffCheck())
                .setLenientExpectationElement(parent)
                .setStrict(isStrict())
                .build();

        List<IBaseDataObject> actualAttachments = attachments != null ? attachments : new ArrayList<>();
        final String differences = PlaceComparisonHelper.checkDifferences(payload, actualAttachments, place.getClass().getName(), diffOptions);
        assertDifferences(differences);
    }

    /**
     * STRICT: Regression comparison using PlaceComparisonHelper.
     *
     * @param answers XML document containing the expected results
     * @param payload The base data object
     * @param attachments The list of child base data objects
     * @param tname the path of the dat file
     * @param parent XML element for the parent
     */
    protected void checkAnswersStrict(Document answers, IBaseDataObject payload, List<IBaseDataObject> attachments, String tname, Element parent) {
        final List<IBaseDataObject> expectedAttachments = new ArrayList<>();
        final IBaseDataObject expectedIbdo = IBaseDataObjectXmlHelper.ibdoFromXml(answers, expectedAttachments, getDecoders(tname));

        final String differences = PlaceComparisonHelper.checkDifferences(
                expectedIbdo, payload,
                expectedAttachments, attachments,
                place.getClass().getName(), getDiffCheck());

        assertDifferences(differences);

        // Strict mode also validates Log Events
        assertIterableEquals(SimplifiedLogEvent.fromXml(parent), actualSimplifiedLogEvents);
    }

    protected void assertDifferences(final String differences) {
        if (differences != null) {
            StringBuilder failureMessage = new StringBuilder(differences);

            if (generateAnswers()) {
                failureMessage
                        .append("\nNOTE: Since 'generateAnswers' is true, ")
                        .append("these differences could indicate non-deterministic processing");
            }

            fail(failureMessage.toString());
        }
    }

    protected void setupPayload(IBaseDataObject payload, Document doc) {
        if (!isStrict()) {
            kff.hash(payload);
        }

        Element root = (doc != null) ? doc.getRootElement() : null;
        if (root == null) {
            return;
        }

        Element setup = root.getChild(SETUP);
        boolean didSetFiletype = false;
        if (setup != null) {
            if (isStrict()) {
                payload.popCurrentForm();
                payload.setFileType(null);
                didSetFiletype = true;
            } else if (!setup.getChildren(INITIAL_FORM).isEmpty()) {
                payload.popCurrentForm();
            }

            IBaseDataObjectXmlHelper.ibdoFromXmlMainElements(setup, payload, getDecoders(payload.getFilename()));

            String fileType = setup.getChildTextTrim(FILE_TYPE);
            if (StringUtils.isNotBlank(fileType)) {
                payload.setFileType(fileType);
                didSetFiletype = true;
            }

            String inputAlternateView = setup.getChildTextTrim(INPUT_ALT_VIEW);
            if (StringUtils.isNotBlank(inputAlternateView)) {
                payload.addAlternateView(inputAlternateView, payload.data());
                payload.setData(INCORRECT_VIEW_MESSAGE);
            }

            final String badAlternateView = setup.getChildTextTrim(BAD_ALT_VIEW);
            if (StringUtils.isNotBlank(badAlternateView)) {
                payload.addAlternateView(badAlternateView, INCORRECT_VIEW_MESSAGE);
            }
        }

        if (!didSetFiletype) {
            payload.setFileType(payload.currentForm());
        }
    }
}
