---
version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    commit-message:
      prefix: dependencies
    labels:
      - "dependencies"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
    groups:
      jackson:
        patterns:
          - "com.fasterxml.jackson*"
      grpc:
        patterns:
          - "io.grpc:*"
      netty:
        patterns:
          - "io.netty:*"
      jetty:
        patterns:
          - "org.eclipse.jetty:*"
          - "org.eclipse.jetty.toolchain:*"
      jersey:
        patterns:
          - "org.glassfish.jersey*"
      junit:
        patterns:
          - "org.junit*"
      metrics:
        patterns:
          - "io.dropwizard.metrics:*"
