---
name: "Lint Codebase"

on: # yamllint disable-line rule:truthy
  push:
    branches: [main, release/**, patch/**]
  pull_request:
    branches: [main, release/**, patch/**]

permissions:
  contents: read
  statuses: write

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Lint Code Base
        uses: oxsecurity/megalinter@0e3ce9b9c8c10effb9b269509cc47ca17cae31c7 # v9.5.0
        env:
          LOG_LEVEL: NOTICE
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EXTENDS: .github/linters/.mega-linter.yml
          # setting this to false means that only changed files will be scanned in each commit
          VALIDATE_ALL_CODEBASE: ${{ github.event_name != 'pull_request' }}
