---
name: "Maven: Publish Site to GitHub Pages"

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
# Release trigger does not work because the release job uses GITHUB_TOKEN
#   release:
#     types: [created]
  pull_request:
    branches: [main, release/**, patch/**] #TODO: Remove after testing

env:
  JAVA_VERSION: "11"
  JAVA_DISTRIBUTION: "corretto"

jobs:
  publish-site:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          cache: "maven"
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml

      - name: Publish site to GitHub Pages
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          mvn site site:stage scm-publish:publish-scm -Pcoverage,pmd -DskipTests